name: Build and Release

on: push

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies and build
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y libssl-dev g++-multilib make libtool curl zip
          chmod u+x ./build.sh
          ./build.sh
          mkdir -p package/addons
          cp -a sourcemod package/addons/
          mkdir -p package/addons/sourcemod/extensions/x64
          cp -a Release/system2.ext.so package/addons/sourcemod/extensions/x64/
          cd package
          zip -y -q -FSr ../package.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: System2-linux
          path: Release/system2.ext.so

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: package.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
