name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-package:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
        sudo apt install libssl-dev g++-multilib make libtool curl
        ./build.sh
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: package-linux-optimize-only
        path: Release/System2.ext.so
